repos:
-   repo: local
    hooks:
    - id: black
      name: Running code formatter
      entry: poetry run black
      language: system
      types: [python]
    - id: flake8
      name: Running flake8 formatter
      entry: poetry run flake8
      language: system
      types: [python]
    - id: mypy
      name: Running mypy formatter
      entry: poetry run mypy
      language: system
      types: [python]
